-- PostgreSQL schema for the Express API using a server-side DATABASE_URL.
-- IDs remain TEXT so existing identifiers can be preserved during import.
-- Timestamps are Ecuador wall-clock values, matching the existing API.

CREATE TABLE IF NOT EXISTS bodegas (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  direccion TEXT,
  latitud DOUBLE PRECISION NOT NULL,
  longitud DOUBLE PRECISION NOT NULL,
  radio_metros INTEGER NOT NULL DEFAULT 100,
  codigo TEXT,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL
    DEFAULT timezone('America/Guayaquil', now())
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bodegas_codigo
  ON bodegas(codigo) WHERE codigo IS NOT NULL;

CREATE TABLE IF NOT EXISTS empleados (
  id TEXT PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  codigo_empleado TEXT NOT NULL UNIQUE,
  cargo TEXT,
  email TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  rol TEXT NOT NULL DEFAULT 'empleado',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  bodega_id TEXT NOT NULL REFERENCES bodegas(id),
  hora_entrada_esperada TEXT NOT NULL DEFAULT '08:00',
  hora_salida_esperada TEXT NOT NULL DEFAULT '17:00',
  tolerancia_min INTEGER NOT NULL DEFAULT 10,
  dias_laborables TEXT NOT NULL DEFAULT '1,2,3,4,5',
  autorizado_todas_bodegas BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL
    DEFAULT timezone('America/Guayaquil', now())
);

CREATE TABLE IF NOT EXISTS registros_asistencia (
  orden BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  id TEXT PRIMARY KEY,
  tipo TEXT NOT NULL,
  timestamp_servidor TIMESTAMP WITHOUT TIME ZONE NOT NULL
    DEFAULT timezone('America/Guayaquil', now()),
  latitud DOUBLE PRECISION NOT NULL,
  longitud DOUBLE PRECISION NOT NULL,
  precision_gps_m DOUBLE PRECISION,
  distancia_a_bodega_m DOUBLE PRECISION NOT NULL,
  valido BOOLEAN NOT NULL,
  motivo_invalido TEXT,
  dispositivo_id TEXT,
  foto_url TEXT,
  empleado_id TEXT NOT NULL REFERENCES empleados(id),
  bodega_id TEXT NOT NULL REFERENCES bodegas(id)
);

CREATE INDEX IF NOT EXISTS idx_registros_empleado
  ON registros_asistencia(empleado_id);
CREATE INDEX IF NOT EXISTS idx_registros_timestamp
  ON registros_asistencia(timestamp_servidor);

CREATE TABLE IF NOT EXISTS auditoria (
  id TEXT PRIMARY KEY,
  usuario_id TEXT NOT NULL REFERENCES empleados(id),
  usuario_email TEXT NOT NULL,
  accion TEXT NOT NULL,
  entidad TEXT NOT NULL,
  entidad_id TEXT NOT NULL,
  detalle TEXT,
  creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL
    DEFAULT timezone('America/Guayaquil', now())
);

CREATE INDEX IF NOT EXISTS idx_auditoria_entidad
  ON auditoria(entidad, entidad_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario
  ON auditoria(usuario_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_creado
  ON auditoria(creado_en);

CREATE TABLE IF NOT EXISTS empleado_bodegas (
  empleado_id TEXT NOT NULL REFERENCES empleados(id),
  bodega_id TEXT NOT NULL REFERENCES bodegas(id),
  creado_en TIMESTAMP WITHOUT TIME ZONE NOT NULL
    DEFAULT timezone('America/Guayaquil', now()),
  PRIMARY KEY (empleado_id, bodega_id)
);

CREATE INDEX IF NOT EXISTS idx_empleado_bodegas_empleado
  ON empleado_bodegas(empleado_id);

-- The Express backend is the only intended application interface. RLS with
-- no policies denies browser/API-key access until a deliberate policy is
-- designed. The private backend connection is responsible for role checks.
ALTER TABLE bodegas ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE registros_asistencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleado_bodegas ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE bodegas, empleados, registros_asistencia, auditoria,
  empleado_bodegas FROM anon, authenticated;
