-- Base PostgreSQL schema converted from the inspected MySQL control_asistencia dump.
-- Intended for a disposable Supabase test project with no conflicting tables.
-- This file creates schema only; it does not import dump rows or drop objects.
BEGIN;

CREATE TABLE public.cargos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.configuracion_sistema (
  clave VARCHAR(100) PRIMARY KEY,
  valor VARCHAR(500) NOT NULL,
  descripcion VARCHAR(255),
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.horarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  nombre VARCHAR(100) NOT NULL,
  tolerancia_minutos INTEGER NOT NULL DEFAULT 0
    CHECK (tolerancia_minutos BETWEEN 0 AND 65535),
  cruza_medianoche BOOLEAN NOT NULL DEFAULT FALSE,
  estado VARCHAR(8) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo', 'inactivo')),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.migrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  version VARCHAR(255) NOT NULL,
  class VARCHAR(255) NOT NULL,
  "group" VARCHAR(255) NOT NULL,
  namespace VARCHAR(255) NOT NULL,
  time INTEGER NOT NULL,
  batch BIGINT NOT NULL CHECK (batch BETWEEN 0 AND 4294967295)
);

CREATE TABLE public.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  nombre VARCHAR(50) NOT NULL UNIQUE,
  descripcion VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.sedes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  nombre VARCHAR(100) NOT NULL,
  direccion VARCHAR(255),
  estado VARCHAR(8) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo', 'inactivo')),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.tipos_incidencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  nombre VARCHAR(100) NOT NULL UNIQUE,
  requiere_aprobacion BOOLEAN NOT NULL DEFAULT TRUE,
  afecta_calculo_asistencia BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.departamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  nombre VARCHAR(100) NOT NULL,
  sede_id BIGINT NOT NULL CHECK (sede_id >= 0)
    REFERENCES public.sedes (id),
  supervisor_id BIGINT CHECK (supervisor_id IS NULL OR supervisor_id >= 0),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.empleados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  codigo_empleado VARCHAR(20) NOT NULL UNIQUE,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  cedula VARCHAR(20) NOT NULL UNIQUE,
  email_personal VARCHAR(150),
  telefono VARCHAR(20),
  sede_id BIGINT NOT NULL CHECK (sede_id >= 0)
    REFERENCES public.sedes (id),
  departamento_id BIGINT NOT NULL CHECK (departamento_id >= 0)
    REFERENCES public.departamentos (id),
  cargo_id BIGINT NOT NULL CHECK (cargo_id >= 0)
    REFERENCES public.cargos (id),
  fecha_ingreso DATE NOT NULL,
  estado VARCHAR(11) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo', 'inactivo', 'vacaciones', 'licencia')),
  supervisor_id BIGINT CHECK (supervisor_id IS NULL OR supervisor_id >= 0),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  deleted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.feriados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  fecha DATE NOT NULL,
  descripcion VARCHAR(150) NOT NULL,
  aplica_todas_sedes BOOLEAN NOT NULL DEFAULT TRUE,
  sede_id BIGINT CHECK (sede_id IS NULL OR sede_id >= 0)
    REFERENCES public.sedes (id),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT feriados_fecha_sede_id_key UNIQUE (fecha, sede_id)
);

CREATE TABLE public.geocercas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  sede_id BIGINT NOT NULL CHECK (sede_id >= 0)
    REFERENCES public.sedes (id),
  nombre VARCHAR(100) NOT NULL,
  latitud_centro NUMERIC(10, 7) NOT NULL,
  longitud_centro NUMERIC(10, 7) NOT NULL,
  radio_metros BIGINT NOT NULL DEFAULT 100
    CHECK (radio_metros BETWEEN 0 AND 4294967295),
  estado VARCHAR(8) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo', 'inactivo')),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.horario_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  horario_id BIGINT NOT NULL CHECK (horario_id >= 0)
    REFERENCES public.horarios (id),
  dia_semana SMALLINT NOT NULL CHECK (dia_semana BETWEEN 0 AND 255),
  hora_entrada TIME WITHOUT TIME ZONE NOT NULL,
  hora_salida TIME WITHOUT TIME ZONE NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT horario_detalle_horario_dia_key UNIQUE (horario_id, dia_semana)
);

CREATE TABLE public.incidencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  empleado_id BIGINT NOT NULL CHECK (empleado_id >= 0)
    REFERENCES public.empleados (id),
  tipo_incidencia_id BIGINT NOT NULL CHECK (tipo_incidencia_id >= 0)
    REFERENCES public.tipos_incidencia (id),
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  motivo TEXT NOT NULL,
  adjunto_url VARCHAR(255),
  estado VARCHAR(9) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aprobado', 'rechazado')),
  revisado_por BIGINT CHECK (revisado_por IS NULL OR revisado_por >= 0),
  revisado_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.asistencias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  empleado_id BIGINT NOT NULL CHECK (empleado_id >= 0)
    REFERENCES public.empleados (id),
  fecha DATE NOT NULL,
  tipo VARCHAR(7) NOT NULL CHECK (tipo IN ('entrada', 'salida')),
  hora_servidor TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  latitud NUMERIC(10, 7) NOT NULL,
  longitud NUMERIC(10, 7) NOT NULL,
  precision_metros NUMERIC(6, 2),
  geocerca_id BIGINT CHECK (geocerca_id IS NULL OR geocerca_id >= 0)
    REFERENCES public.geocercas (id),
  distancia_metros NUMERIC(8, 2) NOT NULL,
  estado_geocerca VARCHAR(6) NOT NULL CHECK (estado_geocerca IN ('dentro', 'fuera')),
  estado_puntualidad VARCHAR(10) NOT NULL DEFAULT 'n/a'
    CHECK (estado_puntualidad IN ('puntual', 'tardanza', 'anticipado', 'n/a')),
  minutos_tardanza INTEGER NOT NULL DEFAULT 0
    CHECK (minutos_tardanza BETWEEN 0 AND 65535),
  ip_origen VARCHAR(45),
  user_agent VARCHAR(255),
  observacion VARCHAR(255),
  aprobado_por BIGINT CHECK (aprobado_por IS NULL OR aprobado_por >= 0),
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  empleado_id BIGINT CHECK (empleado_id IS NULL OR empleado_id >= 0)
    REFERENCES public.empleados (id),
  rol_id BIGINT NOT NULL CHECK (rol_id >= 0)
    REFERENCES public.roles (id),
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  estado VARCHAR(9) NOT NULL DEFAULT 'activo'
    CHECK (estado IN ('activo', 'inactivo', 'bloqueado')),
  intentos_fallidos SMALLINT NOT NULL DEFAULT 0
    CHECK (intentos_fallidos BETWEEN 0 AND 255),
  ultimo_login_at TIMESTAMP WITHOUT TIME ZONE,
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  deleted_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.auditoria_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  usuario_id BIGINT CHECK (usuario_id IS NULL OR usuario_id >= 0)
    REFERENCES public.usuarios (id),
  accion VARCHAR(100) NOT NULL,
  entidad VARCHAR(100) NOT NULL,
  entidad_id BIGINT CHECK (entidad_id IS NULL OR entidad_id >= 0),
  datos_antes JSON,
  datos_despues JSON,
  ip_origen VARCHAR(45),
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.empleado_horario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  empleado_id BIGINT NOT NULL CHECK (empleado_id >= 0)
    REFERENCES public.empleados (id),
  horario_id BIGINT NOT NULL CHECK (horario_id >= 0)
    REFERENCES public.horarios (id),
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE,
  created_by BIGINT CHECK (created_by IS NULL OR created_by >= 0),
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.notificaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  usuario_id BIGINT NOT NULL CHECK (usuario_id >= 0)
    REFERENCES public.usuarios (id),
  tipo VARCHAR(50) NOT NULL,
  titulo VARCHAR(150) NOT NULL,
  mensaje VARCHAR(500) NOT NULL,
  leido BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE public.refresh_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id >= 0),
  usuario_id BIGINT NOT NULL CHECK (usuario_id >= 0)
    REFERENCES public.usuarios (id),
  token_hash CHAR(64) NOT NULL UNIQUE,
  expira_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  revocado BOOLEAN NOT NULL DEFAULT FALSE,
  ip_origen VARCHAR(45),
  created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE INDEX departamentos_sede_id_idx ON public.departamentos (sede_id);
CREATE INDEX departamentos_supervisor_id_idx ON public.departamentos (supervisor_id);
CREATE INDEX empleados_sede_id_idx ON public.empleados (sede_id);
CREATE INDEX empleados_departamento_id_idx ON public.empleados (departamento_id);
CREATE INDEX empleados_cargo_id_idx ON public.empleados (cargo_id);
CREATE INDEX empleados_supervisor_id_idx ON public.empleados (supervisor_id);
CREATE INDEX feriados_sede_id_idx ON public.feriados (sede_id);
CREATE INDEX geocercas_sede_id_idx ON public.geocercas (sede_id);
CREATE INDEX horario_detalle_horario_id_idx ON public.horario_detalle (horario_id);
CREATE INDEX incidencias_tipo_incidencia_id_idx ON public.incidencias (tipo_incidencia_id);
CREATE INDEX incidencias_revisado_por_idx ON public.incidencias (revisado_por);
CREATE INDEX incidencias_empleado_estado_idx ON public.incidencias (empleado_id, estado);
CREATE INDEX asistencias_geocerca_id_idx ON public.asistencias (geocerca_id);
CREATE INDEX asistencias_aprobado_por_idx ON public.asistencias (aprobado_por);
CREATE INDEX asistencias_empleado_fecha_idx ON public.asistencias (empleado_id, fecha);
CREATE INDEX asistencias_fecha_idx ON public.asistencias (fecha);
CREATE INDEX usuarios_empleado_id_idx ON public.usuarios (empleado_id);
CREATE INDEX usuarios_rol_id_idx ON public.usuarios (rol_id);
CREATE INDEX auditoria_log_usuario_id_idx ON public.auditoria_log (usuario_id);
CREATE INDEX auditoria_log_entidad_idx ON public.auditoria_log (entidad, entidad_id);
CREATE INDEX empleado_horario_horario_id_idx ON public.empleado_horario (horario_id);
CREATE INDEX empleado_horario_created_by_idx ON public.empleado_horario (created_by);
CREATE INDEX empleado_horario_empleado_fecha_idx ON public.empleado_horario (empleado_id, fecha_inicio);
CREATE INDEX notificaciones_usuario_leido_idx ON public.notificaciones (usuario_id, leido);
CREATE INDEX refresh_tokens_usuario_revocado_idx ON public.refresh_tokens (usuario_id, revocado);

-- The confirmed supervisor and approving-user relationships are added by the
-- following versioned migration, which also makes the department/employee cycle
-- deferrable for the independent data importer.

ALTER TABLE public.cargos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sedes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_incidencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feriados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.geocercas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horario_detalle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asistencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auditoria_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empleado_horario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refresh_tokens ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  public.cargos,
  public.configuracion_sistema,
  public.horarios,
  public.migrations,
  public.roles,
  public.sedes,
  public.tipos_incidencia,
  public.departamentos,
  public.empleados,
  public.feriados,
  public.geocercas,
  public.horario_detalle,
  public.incidencias,
  public.asistencias,
  public.usuarios,
  public.auditoria_log,
  public.empleado_horario,
  public.notificaciones,
  public.refresh_tokens
FROM anon, authenticated;

COMMIT;
